### ISSUE TITLE
Using it in TableView

### ISSUE THREAD

**Issue by ikashkuta** [joshaber/SwiftBox#2]
Hello Josh!

Cool project, first step in bringing technologies from React Native to real native code, without js! I wonder if this can be used to calculate layout of reusable cells in table view. It seems to be nice fit there since you have to provide height of cell before you provide actual cell to table view. Also, it enables easy caching of cells layout and simple reuse model where views and layout of views already separated from each other.

My question is there any way to calculate height with fixed width? Cells can have different heights that depends on content size (text size in my case) so in first we have to have some way to provide information about text size then calculate height and other stuff then apply in to view hierarchy.

As I see I should calculate text size by hand, then create Node hierarchy with that sizes and then ask about final height. Any thoughts how can it be?

**Comment by joshaber** [comment]
>My question is there any way to calculate height with fixed width?

The short answer is not really. `css-layout` works at the point where you already know<sup>1</sup> the size of the nodes, but want to know how they should be positioned. This makes the algorithm extremely general, but it also means it's not the whole piece of the puzzle. Somewhere, something has to tell it how big nodes should be.

<sup>1</sup>That's kind of a lie because `flex` will size the major axis if you want, but it's not dependent on the content.

>As I see I should calculate text size by hand, then create Node hierarchy with that sizes and then ask about final height.

Right. It'd be nice to include a general "size this text" algorithm in SwiftBox, but sizing text is pretty [infamously](https://github.com/WebKit/webkit/blob/e5e94e454b97a7022cc4616daa14f720c5305958/Source/WebCore/platform/graphics/mac/SimpleFontDataMac.mm#L196-L203) [terrible](https://code.google.com/p/chromium/issues/detail?id=445830#c9).
